### ISSUE TITLE
some easy util upgrades

### ISSUE THREAD

**Issue by hmontero1205** [hmontero1205/pygrader#1]
- `compile_code()` should optionally take a Makefile target
- `prompt_continue()` should optionally take a msg to print instead of just "Press enter to continue"
[ transferred from cs4118/pygrader ]

**Comment by patawan** [comment]
I think I can take care of these! Can I help out?

**Comment by hmontero1205** [comment]
Sure -- thank you!

**Comment by patawan** [comment]
PR #7  to complete this enhancement.
